# Generated by Django 5.2.9 on 2025-12-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=15)),
                ('car_number', models.CharField(help_text='Vehicle registration number', max_length=20)),
                ('wash_package', models.CharField(choices=[('basic', 'Basic Wash - ₹299'), ('premium', 'Premium Wash - ₹599'), ('deluxe', 'Deluxe Detailing - ₹999')], help_text='Selected wash package', max_length=20)),
                ('booking_date', models.DateField(help_text='Preferred service date')),
                ('booking_time', models.TimeField(help_text='Preferred service time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
