# Generated by Django 5.2.9 on 2025-12-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare_app', '0002_carwashbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=15)),
                ('car_number', models.CharField(help_text='Vehicle registration number', max_length=20)),
                ('service_category', models.CharField(choices=[('basic-maintenance', 'Basic Maintenance'), ('mechanical-repairs', 'Mechanical Repairs'), ('electrical-electronics', 'Electrical & Electronics'), ('ac-climate-control', 'AC & Climate Control'), ('tyre-wheel', 'Tyre & Wheel'), ('inspection-diagnostics', 'Inspection & Diagnostics'), ('pre-delivery-inspection', 'Pre-Delivery Inspection')], help_text='Selected service category', max_length=50)),
                ('booking_date', models.DateField(help_text='Preferred service date')),
                ('booking_time', models.TimeField(help_text='Preferred service time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Booking',
                'verbose_name_plural': 'Service Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
