# Generated by Django 5.2.9 on 2025-12-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare_app', '0003_servicebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
