# Generated by Django 5.2.9 on 2025-12-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare_app', '0004_delete_contactmessage_delete_product_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashbooking',
            name='address',
            field=models.TextField(default='N/A', help_text="Customer's address for car pickup/delivery"),
            preserve_default=False,
        ),
    ]
