# Generated by Django 5.2.9 on 2025-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare_app', '0005_carwashbooking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='address',
            field=models.TextField(default='N/A', help_text="Customer's address for service location"),
            preserve_default=False,
        ),
    ]
